[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "target.json"

[target.target]
rustflags = [
            "-C", "link-arg=-Tlinker.ld",
]