[build]
target = "target.json"
# Move it here! This tells Cargo how to handle build-std
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.target]
rustflags = [
        "-C", "link-arg=-Tlinker.ld",
]